from __future__ import annotations
import json
from pathlib import Path
import pandas as pd,numpy as np,matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1];out=ROOT/'results/global_operator';rep=ROOT/'reports';fig=ROOT/'figures/global_operator';rep.mkdir(exist_ok=True);fig.mkdir(parents=True,exist_ok=True)
te=pd.read_csv(out/'test_scenario_metrics.csv');va=pd.read_csv(out/'val_scenario_metrics.csv');h0=pd.read_csv(out/'h0_rollout_metrics.csv');rt=pd.read_csv(out/'runtime_benchmark.csv');tl=pd.read_csv(out/'training_log.csv');
summary={'dataset':{'train':160,'validation':20,'test':20,'h0_excluded':True},'architecture':json.loads((ROOT/'models/global_operator/config.json').read_text())['selected'],'training_steps':int(tl.step.max()),'best_validation_metric':'NOT_AVAILABLE: checkpoint selection was absent in first launcher','test_mean':te.mean(numeric_only=True).to_dict(),'h0_final':h0.iloc[-1].to_dict(),'runtime_s':{'median':float(rt.wall_s.median()),'mean':float(rt.wall_s.mean()),'p95':float(rt.wall_s.quantile(.95))},'engineering_metrics':'NOT_CURRENTLY_FIELD_DERIVABLE from retained state schema; no solver station-flux state is available','front_metrics':'NOT_CURRENTLY_FIELD_DERIVABLE with retained state schema','result_status':'FROZEN_CANDIDATE_EVALUATED_NOT_PUBLICATION_READY: long-rollout wet footprint and field errors are high'}
(rep/'GLOBAL_OPERATOR_BASELINE.json').write_text(json.dumps(summary,indent=2));(rep/'GLOBAL_OPERATOR_BASELINE.md').write_text('# Global Neural Operator baseline\n\n```json\n'+json.dumps(summary,indent=2)+'\n```\n\nThis is a descriptive frozen-checkpoint evaluation. It must not be presented as an accuracy-successful surrogate or as observational truth.\n')
plt.style.use('seaborn-v0_8-whitegrid');ax=tl.plot(x='step',y='train_total_loss',title='Global-FNO stochastic training loss');ax.figure.savefig(fig/'training_curve.png',dpi=180,bbox_inches='tight');plt.close(ax.figure);ax=te.groupby('time_s').h_rell2.mean().plot(marker='o',title='Test h RelL2 by rollout time');ax.set_ylabel('h RelL2');ax.figure.savefig(fig/'validation_rollout_error_vs_time.png',dpi=180,bbox_inches='tight');plt.close(ax.figure);pd.DataFrame({'global_fno_rollout_s':rt.wall_s}).plot(kind='box',title='Global-FNO 144-step runtime');plt.savefig(fig/'runtime_comparison.png',dpi=180,bbox_inches='tight');plt.close()
