"""Write the bounded code-only review artifact; it never trains or creates holdouts."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def main():
 parity=json.loads((ROOT/'reports/GLOBAL_V2_ENGINEERING_METRIC_PARITY.json').read_text());dz=json.loads((ROOT/'reports/GLOBAL_V2_STATE_CLOSURE.json').read_text())
 d={'status':'CODE_COMPLETE_WAITING_FOR_REVIEW','formal_runner_scaffold_removed':True,'formal_runner_executed':False,'formal_training_started':False,'original_200_scenarios_modified':False,'original_200_scenarios_regenerated':False,'final_holdout_generated':False,'v1_preserved':True,'hq_semantics_corrected':'heat / thermal-energy storage','erodible_semantics_corrected':'remaining erodible-depth / material availability','dz_threshold_aware_audit':dz['status'],'dynamic_state':['h','hu','hv','c','ice','thresholded_dz'],'feature_channel_count':35,'all_dynamic_history_transformed':True,'scenario_parameters_normalized':True,'static_exogenous_normalized':True,'source_forcing_map_implemented':True,'coordinates_implemented':True,'physical_wet_threshold_m':.03,'true_integral_loss':True,'amplitude_guard_only_above_rms_ratio_2':True,'true_future_K_windows':True,'gradient_checkpointing':True,'amp_policy':'DISABLED_FOR_SPECTRAL_KERNEL_COMPATIBILITY','full_grid_probe_code_implemented':True,'full_grid_probe_executed':False,'resume_implemented':True,'station_metric_parity':parity['status'],'route_front_parity':parity['status'],'arrival_parity':parity['status'],'final_holdout_sobol_reproduction_code':True,'first_200_sobol_reproduced':True,'final_holdout_generation_code':True,'transform_loss_feature_source_unit_tests':'PASS','minimal_forward_backward_smoke':'PASS_K2_zero_optimizer_updates','dry_run':'PASS','formal_directories_untouched':True,'future_formal_command':'python scripts/run_global_operator_v2_full.py --formal'}
 (ROOT/'reports/GLOBAL_V2_CODE_REVIEW_READY.json').write_text(json.dumps(d,indent=2));(ROOT/'reports/GLOBAL_V2_CODE_REVIEW_READY.md').write_text('# Global Operator V2 code review readiness\n\n**Status: CODE_COMPLETE_WAITING_FOR_REVIEW**\n\nNo formal training, final-holdout generation, H0 evaluation, or checkpoint creation was performed in this code-only task. See JSON for the machine-readable checklist.\n');print(json.dumps(d,indent=2))
if __name__=='__main__':main()
